from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.orm import Session

from app.api.dependencies import (
    record_audit_event,
    require_sport_access,
    require_user,
)
from app.db.session import get_db
from app.models.user import User
from app.schemas.submissions import SubmitAdjustmentsRequest, SubmittedAdjustmentResponse
from app.services.emailer import EmailConfigurationError, send_email_with_attachments
from app.services.submission_workflow import (
    PreparedSubmissionChange,
    create_submission_with_adjustments,
    generate_submission_artifacts,
    persist_generated_artifacts,
)

router = APIRouter(prefix="/submissions", tags=["submissions"])


@router.post("/adjustments", response_model=SubmittedAdjustmentResponse)
def submit_adjustments(
    payload: SubmitAdjustmentsRequest,
    request: Request,
    db: Session = Depends(get_db),
    user: User = Depends(require_user),
) -> SubmittedAdjustmentResponse:
    require_sport_access(payload.sport_id, user)

    try:
        workflow = create_submission_with_adjustments(
            db=db,
            sport_id=payload.sport_id,
            submitted_by_user_id=user.id,
            source="UI",
            comment=payload.comment,
            changes=[
                PreparedSubmissionChange(
                    membership_id=change.membership_id,
                    after_values={
                        field: str(value)
                        for field, value in change.after_values.model_dump().items()
                    },
                )
                for change in payload.changes
            ],
        )
    except ValueError as caught:
        raise HTTPException(status_code=400, detail=str(caught)) from caught

    generated_artifacts = generate_submission_artifacts(
        db=db,
        submission=workflow.submission,
        adjustments=workflow.adjustments,
        submitted_by_name=user.display_name or user.email,
        comment=payload.comment,
    )

    try:
        send_email_with_attachments(
            recipient_email=str(payload.recipient_email),
            subject=f"Athletic aid adjustment submission - {workflow.submission.id}",
            body=build_email_body(
                user_name=user.display_name or user.email,
                comment=payload.comment,
                adjustments_created=len(workflow.adjustments),
            ),
            attachments=[artifact.path for artifact in generated_artifacts],
        )
    except EmailConfigurationError as caught:
        raise HTTPException(status_code=500, detail=str(caught)) from caught
    except Exception as caught:  # pragma: no cover - defensive path
        raise HTTPException(status_code=500, detail=f"Email send failed: {caught}") from caught

    persist_generated_artifacts(
        db=db,
        submission_id=workflow.submission.id,
        recipient_email=str(payload.recipient_email),
        generated_artifacts=generated_artifacts,
    )

    record_audit_event(
        db,
        user_id=user.id,
        action="SUBMIT_ADJUSTMENTS",
        entity_type="submission",
        entity_id=str(workflow.submission.id),
        request=request,
        after={
            "submission_id": str(workflow.submission.id),
            "sport_id": payload.sport_id,
            "adjustments_created": len(workflow.adjustments),
            "recipient_email": str(payload.recipient_email),
            "artifacts_created": len(generated_artifacts),
        },
    )
    db.commit()
    return SubmittedAdjustmentResponse(
        submission_id=workflow.submission.id,
        adjustments_created=len(workflow.adjustments),
        artifacts_created=len(generated_artifacts),
        recipient_email=payload.recipient_email,
    )


def build_email_body(*, user_name: str, comment: str | None, adjustments_created: int) -> str:
    lines = [
        "This email was generated by the Athletic Scholarship Management MVP.",
        "",
        f"Submitted by: {user_name}",
        f"Adjustments included: {adjustments_created}",
    ]
    if comment:
        lines.extend(["", "Submission note:", comment])
    lines.extend(
        [
            "",
            "Attachments:",
            "- Adjustment of Aid workbook(s)",
            "- Tender PDF(s)",
        ]
    )
    return "\n".join(lines)
